name: Print name

on:
  push:
    branches:
      - main
  workflow_dispatch:   # allows manual trigger

jobs:
  print-name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print name
        run: echo "Hello, Raj!"
